#<%= load('config/secret-manager.rb') %>
default: &default
  socket: /var/run/mysqld/mysqld.sock # para obtener esta vriable se ejecuta el comando 'mysql -uroot -p' y 'show variables like 'sokect''
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV["DB_POOL"] || 5  %>
  database: <%= $secret['dbInstanceIdentifier'] %>
  username: <%= $secret['username'] %>
  password: <%= $secret['password'] %>
  host: <%= $secret['host'] %>
  port:  <%= $secret['port']%>
  url: <%= ENV['DATABASE_URL'] %> # takes higher precedence than other settings
  reconnect: true

development:
  <<: *default
  database: <%= $secret['dbInstanceIdentifier']%>

test:
  <<: *default
  database: <%= $secret['dbInstanceIdentifier']%>

production:
  <<: *default
  database: <%= $secret['dbInstanceIdentifier']%>
  url: <%= ENV['DATABASE_URL'] %>
